name: build

on: [push, pull_request]

jobs:

  build-and-test:
    name: build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest","windows-latest"]
        python-version: ["3.7"]
    steps:
      - uses: actions/checkout@v2
    
      - name: Setup Miniconda
        uses: goanpeca/setup-miniconda@v1.2.0
        with:
         activate-environment: pyross
         environment-file: environment.yml
         python-version: ${{ matrix.python-version }}
      - name: make-pyross
        shell: bash -l {0}
        run: |
          conda activate pyross
          make
      - name: test-pyross
        shell: bash -l {0}
        run: |
          make test

